### ISSUE TITLE
Postgresql support

### ISSUE THREAD

**Issue by ojosdegris** [nreco/nicnet#2]
Hi guys, are there plans to include postgres support ?

**Comment by VitaliyMF** [comment]
Hi Victor,

since Postgres has stable ADO.NET provider (Npgsql) its connector can be easily added. You may glance at the [Mysql NI.Data connector](https://github.com/nreco/nicnet/tree/master/src/NI.Data.MySql) and create connector for Postgres by yourself if you need it ASAP. Feel free to contact me in case of any complications.

**Comment by VitaliyMF** [comment]
Several days I've released new library for lightweight, provider-independent data access for .NET Core and old .NET 4.x projects: [NReco.Data](https://github.com/nreco/data). NReco.Data can be used with any ADO.NET provider, including MsSql, PostgreSql, MySql, Sqlite etc.

**Comment by ojosdegris** [comment]
@VitaliyMF  thank you, I will take a look!
